/*
Over Engineered Calculator

This is a sample API for an over engineered calculator for a coding test

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the HelpersErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HelpersErrorResponse{}

// HelpersErrorResponse struct for HelpersErrorResponse
type HelpersErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// NewHelpersErrorResponse instantiates a new HelpersErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHelpersErrorResponse() *HelpersErrorResponse {
	this := HelpersErrorResponse{}
	return &this
}

// NewHelpersErrorResponseWithDefaults instantiates a new HelpersErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHelpersErrorResponseWithDefaults() *HelpersErrorResponse {
	this := HelpersErrorResponse{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *HelpersErrorResponse) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HelpersErrorResponse) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *HelpersErrorResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *HelpersErrorResponse) SetError(v string) {
	o.Error = &v
}

func (o HelpersErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HelpersErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableHelpersErrorResponse struct {
	value *HelpersErrorResponse
	isSet bool
}

func (v NullableHelpersErrorResponse) Get() *HelpersErrorResponse {
	return v.value
}

func (v *NullableHelpersErrorResponse) Set(val *HelpersErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHelpersErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHelpersErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHelpersErrorResponse(val *HelpersErrorResponse) *NullableHelpersErrorResponse {
	return &NullableHelpersErrorResponse{value: val, isSet: true}
}

func (v NullableHelpersErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHelpersErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


